import './bootstrap';

import Alpine from 'alpinejs';
import Chart from 'chart.js/auto';
import {
    ArrowRight,
    Banknote,
    Bell,
    Bot,
    Boxes,
    ChartColumn,
    ChartNoAxesCombined,
    ChartSpline,
    Check,
    CircleAlert,
    ClipboardList,
    Clock3,
    CreditCard,
    Download,
    Globe,
    Globe2,
    History,
    KeyRound,
    Landmark,
    LayoutDashboard,
    LockKeyhole,
    LogIn,
    LogOut,
    Mail,
    MapPin,
    MessageCircle,
    Package,
    PackageCheck,
    PackagePlus,
    Phone,
    Printer,
    Radar,
    RefreshCw,
    ScanSearch,
    Send,
    ShieldAlert,
    ShieldCheck,
    Star,
    Moon,
    Sun,
    Target,
    Truck,
    UserPlus,
    UserRound,
    Users,
    WalletCards,
    createIcons,
} from 'lucide';

window.Alpine = Alpine;
window.Chart = Chart;

Alpine.start();

document.addEventListener('DOMContentLoaded', () => {
    createIcons({
        icons: {
            ArrowRight,
            Banknote,
            Bell,
            Bot,
            Boxes,
            ChartColumn,
            ChartNoAxesCombined,
            ChartSpline,
            Check,
            CircleAlert,
            ClipboardList,
            Clock3,
            CreditCard,
            Download,
            Globe,
            Globe2,
            History,
            KeyRound,
            Landmark,
            LayoutDashboard,
            LockKeyhole,
            LogIn,
            LogOut,
            Mail,
            MapPin,
            MessageCircle,
            Package,
            PackageCheck,
            PackagePlus,
            Phone,
            Printer,
            Radar,
            RefreshCw,
            ScanSearch,
            Send,
            ShieldAlert,
            ShieldCheck,
            Star,
            Moon,
            Sun,
            Target,
            Truck,
            UserPlus,
            UserRound,
            Users,
            WalletCards,
        },
    });
});
